(* Generated by .millet/gen.py. Do not edit by hand. *)
(* This file is for Millet only; it is not part of the MLWorks build. *)

val require : string -> unit = fn _ => ()

structure Array =
  struct
    datatype 'a array = MLWorks_Array_array
    datatype 'a vector = MLWorks_Array_vector
    val maxLen : int = raise Fail "MLWorks Millet shim: Array.maxLen"
    val array : (int * 'a) -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array.array")
    val fromList : 'a list -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array.fromList")
    val tabulate : (int * (int -> 'a)) -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array.tabulate")
    val length : 'a array -> int = (fn _ => raise Fail "MLWorks Millet shim: Array.length")
    val sub : ('a array * int) -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Array.sub")
    val update : ('a array * int * 'a) -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.update")
    val extract : ('a array * int * int option) -> 'a vector = (fn _ => raise Fail "MLWorks Millet shim: Array.extract")
    val copy : {src : 'a array, si : int, len : int option, dst : 'a array, di : int} -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.copy")
    val copyVec : {src : 'a vector, si : int, len : int option, dst : 'a array, di : int} -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.copyVec")
    val appi : ((int * 'a) -> unit) -> ('a array * int * int option) -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.appi")
    val app : ('a -> unit) -> 'a array -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.app")
    val foldli : ((int * 'a * 'b) -> 'b) -> 'b -> ('a array * int * int option) -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array.foldli")
    val foldri : ((int * 'a * 'b) -> 'b) -> 'b -> ('a array * int * int option) -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array.foldri")
    val foldl : (('a * 'b) -> 'b) -> 'b -> 'a array -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array.foldl")
    val foldr : (('a * 'b) -> 'b) -> 'b -> 'a array -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array.foldr")
    val modifyi : ((int * 'a) -> 'a) -> ('a array * int * int option) -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.modifyi")
    val modify : ('a -> 'a) -> 'a array -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array.modify")
  end

structure Array2 =
  struct
    datatype 'a array = MLWorks_Array2_array
    type 'a region = { base : 'a array, row : int, col : int, nrows:int option, ncols : int option}
    datatype traversal = RowMajor | ColMajor
    val array : int * int * 'a -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array2.array")
    val fromList : 'a list list -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array2.fromList")
    val tabulate : traversal -> int * int * (int * int -> 'a) -> 'a array = (fn _ => raise Fail "MLWorks Millet shim: Array2.tabulate")
    val sub : 'a array * int * int -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Array2.sub")
    val update : 'a array * int * int * 'a -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.update")
    val dimensions : 'a array -> int * int = (fn _ => raise Fail "MLWorks Millet shim: Array2.dimensions")
    val nCols : 'a array -> int = (fn _ => raise Fail "MLWorks Millet shim: Array2.nCols")
    val nRows : 'a array -> int = (fn _ => raise Fail "MLWorks Millet shim: Array2.nRows")
    val row : 'a array * int -> 'a Vector.vector = (fn _ => raise Fail "MLWorks Millet shim: Array2.row")
    val column : 'a array * int -> 'a Vector.vector = (fn _ => raise Fail "MLWorks Millet shim: Array2.column")
    val copy : {src : 'a region, dst : 'a array, dst_row : int, dst_col : int} -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.copy")
    val appi : traversal -> ((int * int * 'a) -> unit) -> 'a region -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.appi")
    val app : traversal -> ('a -> unit) -> 'a array -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.app")
    val modifyi : traversal -> ((int * int * 'a) -> 'a) -> 'a region -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.modifyi")
    val modify : traversal -> ('a -> 'a) -> 'a array -> unit = (fn _ => raise Fail "MLWorks Millet shim: Array2.modify")
    val foldi : traversal -> (int * int * 'a * 'b -> 'b) -> 'b -> 'a region -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array2.foldi")
    val fold : traversal -> (('a * 'b) -> 'b) -> 'b -> 'a array -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Array2.fold")
  end

structure Bool =
  struct
    val not : bool -> bool = (fn _ => raise Fail "MLWorks Millet shim: Bool.not")
    val fromString : string -> bool option = (fn _ => raise Fail "MLWorks Millet shim: Bool.fromString")
    val scan : (char, 'a) StringCvt.reader -> 'a -> (bool * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Bool.scan")
    val toString : bool -> string = (fn _ => raise Fail "MLWorks Millet shim: Bool.toString")
  end

structure Byte =
  struct
    val byteToChar : Word8.word -> char = (fn _ => raise Fail "MLWorks Millet shim: Byte.byteToChar")
    val charToByte : char -> Word8.word = (fn _ => raise Fail "MLWorks Millet shim: Byte.charToByte")
    val bytesToString : Word8Vector.vector -> string = (fn _ => raise Fail "MLWorks Millet shim: Byte.bytesToString")
    val stringToBytes : string -> Word8Vector.vector = (fn _ => raise Fail "MLWorks Millet shim: Byte.stringToBytes")
    val unpackStringVec : (Word8Vector.vector * int * int option) -> string = (fn _ => raise Fail "MLWorks Millet shim: Byte.unpackStringVec")
    val unpackString : (Word8Array.array * int * int option) -> string = (fn _ => raise Fail "MLWorks Millet shim: Byte.unpackString")
    val packString : (Word8Array.array * int * Substring.substring) -> unit = (fn _ => raise Fail "MLWorks Millet shim: Byte.packString")
  end

structure Char =
  struct
    type char = char
    type string = string
    val maxOrd : int = raise Fail "MLWorks Millet shim: Char.maxOrd"
    val minChar : char = raise Fail "MLWorks Millet shim: Char.minChar"
    val maxChar : char = raise Fail "MLWorks Millet shim: Char.maxChar"
    val chr : int -> char = (fn _ => raise Fail "MLWorks Millet shim: Char.chr")
    val ord : char -> int = (fn _ => raise Fail "MLWorks Millet shim: Char.ord")
    val succ : char -> char = (fn _ => raise Fail "MLWorks Millet shim: Char.succ")
    val pred : char -> char = (fn _ => raise Fail "MLWorks Millet shim: Char.pred")
    val op < : (char * char) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.<")
    val op <= : (char * char) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.<=")
    val op > : (char * char) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.>")
    val op >= : (char * char) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.>=")
    val compare : (char * char) -> order = (fn _ => raise Fail "MLWorks Millet shim: Char.compare")
    val contains : string -> char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.contains")
    val notContains : string -> char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.notContains")
    val isLower : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isLower")
    val isUpper : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isUpper")
    val isDigit : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isDigit")
    val isAlpha : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isAlpha")
    val isAlphaNum : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isAlphaNum")
    val isAscii : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isAscii")
    val isSpace : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isSpace")
    val toLower : char -> char = (fn _ => raise Fail "MLWorks Millet shim: Char.toLower")
    val toUpper : char -> char = (fn _ => raise Fail "MLWorks Millet shim: Char.toUpper")
    val isCntrl : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isCntrl")
    val isGraph : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isGraph")
    val isHexDigit : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isHexDigit")
    val isPrint : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isPrint")
    val isPunct : char -> bool = (fn _ => raise Fail "MLWorks Millet shim: Char.isPunct")
    val fromString : string -> char option = (fn _ => raise Fail "MLWorks Millet shim: Char.fromString")
    val toString : char -> string = (fn _ => raise Fail "MLWorks Millet shim: Char.toString")
    val scan : (char, 'a) StringCvt.reader -> 'a -> (char * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Char.scan")
    val fromCString : string -> char option = (fn _ => raise Fail "MLWorks Millet shim: Char.fromCString")
    val toCString : char -> string = (fn _ => raise Fail "MLWorks Millet shim: Char.toCString")
  end

structure CommandLine =
  struct
    val name : unit -> string = (fn _ => raise Fail "MLWorks Millet shim: CommandLine.name")
    val arguments : unit -> string list = (fn _ => raise Fail "MLWorks Millet shim: CommandLine.arguments")
  end

structure Date =
  struct
    datatype weekday = Mon | Tue | Wed | Thu | Fri | Sat | Sun
    datatype month = Jan | Feb | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec
    datatype date = MLWorks_Date_date
    exception Date
    val year : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.year")
    val month : date -> month = (fn _ => raise Fail "MLWorks Millet shim: Date.month")
    val day : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.day")
    val hour : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.hour")
    val minute : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.minute")
    val second : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.second")
    val weekDay : date -> weekday = (fn _ => raise Fail "MLWorks Millet shim: Date.weekDay")
    val yearDay : date -> int = (fn _ => raise Fail "MLWorks Millet shim: Date.yearDay")
    val offset : date -> Time.time option = (fn _ => raise Fail "MLWorks Millet shim: Date.offset")
    val isDst : date -> bool option = (fn _ => raise Fail "MLWorks Millet shim: Date.isDst")
    val date : { year : int, month : month, day : int, hour : int, minute : int, second : int, offset : Time.time option } -> date = (fn _ => raise Fail "MLWorks Millet shim: Date.date")
    val localOffset : unit -> Time.time = (fn _ => raise Fail "MLWorks Millet shim: Date.localOffset")
    val fromTimeLocal : Time.time -> date = (fn _ => raise Fail "MLWorks Millet shim: Date.fromTimeLocal")
    val fromTimeUniv : Time.time -> date = (fn _ => raise Fail "MLWorks Millet shim: Date.fromTimeUniv")
    val toTime : date -> Time.time = (fn _ => raise Fail "MLWorks Millet shim: Date.toTime")
    val toString : date -> string = (fn _ => raise Fail "MLWorks Millet shim: Date.toString")
    val fmt : string -> date -> string = (fn _ => raise Fail "MLWorks Millet shim: Date.fmt")
    val fromString : string -> date option = (fn _ => raise Fail "MLWorks Millet shim: Date.fromString")
    val scan : (char, 'a) StringCvt.reader -> (date, 'a) StringCvt.reader = (fn _ => raise Fail "MLWorks Millet shim: Date.scan")
    val compare : (date * date) -> order = (fn _ => raise Fail "MLWorks Millet shim: Date.compare")
  end

structure General =
  struct
    type unit = unit
    type exn = exn
    exception Bind
    exception Match
    exception Subscript
    exception Size
    exception Overflow
    exception Domain
    exception Div
    exception Chr
    exception Fail of string
    val exnName : exn -> string = (fn _ => raise Fail "MLWorks Millet shim: General.exnName")
    val exnMessage : exn -> string = (fn _ => raise Fail "MLWorks Millet shim: General.exnMessage")
    datatype order = LESS | EQUAL | GREATER
    val op <> : (''a * ''a) -> bool = (fn _ => raise Fail "MLWorks Millet shim: General.<>")
    val op ! : 'a ref -> 'a = (fn _ => raise Fail "MLWorks Millet shim: General.!")
    val op := : ('a ref * 'a) -> unit = (fn _ => raise Fail "MLWorks Millet shim: General.:=")
    val op o : (('b -> 'c) * ('a -> 'b)) -> 'a -> 'c = (fn _ => raise Fail "MLWorks Millet shim: General.o")
    val op before : ('a * unit) -> 'a = (fn _ => raise Fail "MLWorks Millet shim: General.before")
    val ignore : 'a -> unit = (fn _ => raise Fail "MLWorks Millet shim: General.ignore")
  end

structure IEEEReal =
  struct
    exception Unordered
    datatype real_order = LESS | EQUAL | GREATER | UNORDERED
    datatype float_class = NAN | INF | ZERO | NORMAL | SUBNORMAL
    datatype rounding_mode = TO_NEAREST | TO_NEGINF | TO_POSINF | TO_ZERO
    val setRoundingMode : rounding_mode -> unit = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.setRoundingMode")
    val getRoundingMode : unit -> rounding_mode = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.getRoundingMode")
    datatype decimal_approx = MLWorks_IEEEReal_decimal_approx
    val class : decimal_approx -> float_class = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.class")
    val signBit : decimal_approx -> bool = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.signBit")
    val digits : decimal_approx -> int list = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.digits")
    val exp : decimal_approx -> int = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.exp")
    val toString : decimal_approx -> string = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.toString")
    val fromString : string -> decimal_approx option = (fn _ => raise Fail "MLWorks Millet shim: IEEEReal.fromString")
  end

structure Int =
  struct
    type int = int
    val toLarge : int -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Int.toLarge")
    val fromLarge : LargeInt.int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.fromLarge")
    val toInt : int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.toInt")
    val fromInt : int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.fromInt")
    val precision : int option = raise Fail "MLWorks Millet shim: Int.precision"
    val minInt : int option = raise Fail "MLWorks Millet shim: Int.minInt"
    val maxInt : int option = raise Fail "MLWorks Millet shim: Int.maxInt"
    val op ~ : int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.~")
    val op * : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.*")
    val op div : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.div")
    val op mod : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.mod")
    val quot : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.quot")
    val rem : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.rem")
    val op + : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.+")
    val op - : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.-")
    val compare : (int * int) -> order = (fn _ => raise Fail "MLWorks Millet shim: Int.compare")
    val op > : int * int -> bool = (fn _ => raise Fail "MLWorks Millet shim: Int.>")
    val op >= : int * int -> bool = (fn _ => raise Fail "MLWorks Millet shim: Int.>=")
    val op < : int * int -> bool = (fn _ => raise Fail "MLWorks Millet shim: Int.<")
    val op <= : int * int -> bool = (fn _ => raise Fail "MLWorks Millet shim: Int.<=")
    val abs : int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.abs")
    val min : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.min")
    val max : int * int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.max")
    val sign : int -> int = (fn _ => raise Fail "MLWorks Millet shim: Int.sign")
    val sameSign : int * int -> bool = (fn _ => raise Fail "MLWorks Millet shim: Int.sameSign")
    val fmt : StringCvt.radix -> int -> string = (fn _ => raise Fail "MLWorks Millet shim: Int.fmt")
    val toString : int -> string = (fn _ => raise Fail "MLWorks Millet shim: Int.toString")
    val fromString : string -> int option = (fn _ => raise Fail "MLWorks Millet shim: Int.fromString")
    val scan : StringCvt.radix -> (char, 'a) StringCvt.reader -> 'a -> (int * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Int.scan")
  end

structure IO =
  struct
    exception Io of {name : string, function : string, cause : exn}
    exception BlockingNotSupported
    exception NonblockingNotSupported
    exception RandomAccessNotSupported
    exception TerminatedStream
    exception ClosedStream
    datatype buffer_mode = NO_BUF | LINE_BUF | BLOCK_BUF
  end

structure List =
  struct
    exception Empty
    val null : 'a list -> bool = (fn _ => raise Fail "MLWorks Millet shim: List.null")
    val length : 'a list -> int = (fn _ => raise Fail "MLWorks Millet shim: List.length")
    val op @ : 'a list * 'a list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.@")
    val hd : 'a list -> 'a = (fn _ => raise Fail "MLWorks Millet shim: List.hd")
    val tl : 'a list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.tl")
    val last : 'a list -> 'a = (fn _ => raise Fail "MLWorks Millet shim: List.last")
    val nth : 'a list * int -> 'a = (fn _ => raise Fail "MLWorks Millet shim: List.nth")
    val take : ('a list * int ) -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.take")
    val drop : ('a list * int ) -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.drop")
    val rev : 'a list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.rev")
    val concat : 'a list list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.concat")
    val revAppend : 'a list * 'a list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.revAppend")
    val app : ('a -> unit) -> 'a list -> unit = (fn _ => raise Fail "MLWorks Millet shim: List.app")
    val map : ('a -> 'b) -> 'a list -> 'b list = (fn _ => raise Fail "MLWorks Millet shim: List.map")
    val mapPartial : ('a -> 'b option) -> 'a list -> 'b list = (fn _ => raise Fail "MLWorks Millet shim: List.mapPartial")
    val find : ('a -> bool) -> 'a list -> 'a option = (fn _ => raise Fail "MLWorks Millet shim: List.find")
    val filter : ('a -> bool) -> 'a list -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.filter")
    val partition : ('a -> bool ) -> 'a list -> ('a list * 'a list) = (fn _ => raise Fail "MLWorks Millet shim: List.partition")
    val foldl : ('a * 'b -> 'b) -> 'b -> 'a list -> 'b = (fn _ => raise Fail "MLWorks Millet shim: List.foldl")
    val foldr : ('a * 'b -> 'b) -> 'b -> 'a list -> 'b = (fn _ => raise Fail "MLWorks Millet shim: List.foldr")
    val exists : ('a -> bool) -> 'a list -> bool = (fn _ => raise Fail "MLWorks Millet shim: List.exists")
    val all : ('a -> bool) -> 'a list -> bool = (fn _ => raise Fail "MLWorks Millet shim: List.all")
    val tabulate : (int * (int -> 'a)) -> 'a list = (fn _ => raise Fail "MLWorks Millet shim: List.tabulate")
  end

structure ListPair =
  struct
    val zip : ('a list * 'b list) -> ('a * 'b) list = (fn _ => raise Fail "MLWorks Millet shim: ListPair.zip")
    val unzip : ('a * 'b) list -> ('a list * 'b list) = (fn _ => raise Fail "MLWorks Millet shim: ListPair.unzip")
    val map : ('a * 'b -> 'c) -> ('a list * 'b list) -> 'c list = (fn _ => raise Fail "MLWorks Millet shim: ListPair.map")
    val app : ('a * 'b -> unit) -> ('a list * 'b list) -> unit = (fn _ => raise Fail "MLWorks Millet shim: ListPair.app")
    val foldl : (('a * 'b * 'c) -> 'c) -> 'c -> ('a list * 'b list) -> 'c = (fn _ => raise Fail "MLWorks Millet shim: ListPair.foldl")
    val foldr : (('a * 'b * 'c) -> 'c) -> 'c -> ('a list * 'b list) -> 'c = (fn _ => raise Fail "MLWorks Millet shim: ListPair.foldr")
    val all : ('a * 'b -> bool) -> ('a list * 'b list) -> bool = (fn _ => raise Fail "MLWorks Millet shim: ListPair.all")
    val exists : ('a * 'b -> bool) -> ('a list * 'b list) -> bool = (fn _ => raise Fail "MLWorks Millet shim: ListPair.exists")
  end

structure Math =
  struct
    type real = real
    val pi : real = raise Fail "MLWorks Millet shim: Math.pi"
    val e : real = raise Fail "MLWorks Millet shim: Math.e"
    val sqrt : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.sqrt")
    val sin : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.sin")
    val cos : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.cos")
    val tan : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.tan")
    val asin : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.asin")
    val acos : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.acos")
    val atan : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.atan")
    val atan2 : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.atan2")
    val exp : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.exp")
    val pow : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.pow")
    val ln : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.ln")
    val log10 : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.log10")
    val sinh : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.sinh")
    val cosh : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.cosh")
    val tanh : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Math.tanh")
  end

structure Option =
  struct
    datatype 'a option = NONE | SOME of 'a
    exception Option
    val isSome : 'a option -> bool = (fn _ => raise Fail "MLWorks Millet shim: Option.isSome")
    val valOf : 'a option -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Option.valOf")
    val getOpt : 'a option * 'a -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Option.getOpt")
    val filter : ('a -> bool) -> 'a -> 'a option = (fn _ => raise Fail "MLWorks Millet shim: Option.filter")
    val map : ('a -> 'b) -> 'a option -> 'b option = (fn _ => raise Fail "MLWorks Millet shim: Option.map")
    val join : 'a option option -> 'a option = (fn _ => raise Fail "MLWorks Millet shim: Option.join")
    val mapPartial : ('a -> 'b option) -> ('a option -> 'b option) = (fn _ => raise Fail "MLWorks Millet shim: Option.mapPartial")
    val compose : (('b -> 'c) * ('a -> 'b option)) -> ('a -> 'c option) = (fn _ => raise Fail "MLWorks Millet shim: Option.compose")
    val composePartial : (('b -> 'c option) * ('a -> 'b option)) -> ('a -> 'c option) = (fn _ => raise Fail "MLWorks Millet shim: Option.composePartial")
  end

structure Real =
  struct
    type real = real
    val radix : int = raise Fail "MLWorks Millet shim: Real.radix"
    val precision : int = raise Fail "MLWorks Millet shim: Real.precision"
    val maxFinite : real = raise Fail "MLWorks Millet shim: Real.maxFinite"
    val minPos : real = raise Fail "MLWorks Millet shim: Real.minPos"
    val minNormalPos : real = raise Fail "MLWorks Millet shim: Real.minNormalPos"
    val posInf : real = raise Fail "MLWorks Millet shim: Real.posInf"
    val negInf : real = raise Fail "MLWorks Millet shim: Real.negInf"
    val op + : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.+")
    val op - : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.-")
    val op * : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.*")
    val op / : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real./")
    val op *+ : real * real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.*+")
    val op *- : real * real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.*-")
    val op ~ : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.~")
    val abs : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.abs")
    val min : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.min")
    val max : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.max")
    val sign : real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.sign")
    val signBit : real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.signBit")
    val sameSign : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.sameSign")
    val copySign : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.copySign")
    val compare : real * real -> order = (fn _ => raise Fail "MLWorks Millet shim: Real.compare")
    val compareReal : real * real -> IEEEReal.real_order = (fn _ => raise Fail "MLWorks Millet shim: Real.compareReal")
    val op < : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.<")
    val op <= : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.<=")
    val op > : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.>")
    val op >= : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.>=")
    val op == : (real * real) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.==")
    val op != : (real * real) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.!=")
    val op ?= : (real * real) -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.?=")
    val unordered : real * real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.unordered")
    val isFinite : real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.isFinite")
    val isNan : real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.isNan")
    val isNormal : real -> bool = (fn _ => raise Fail "MLWorks Millet shim: Real.isNormal")
    val class : real -> IEEEReal.float_class = (fn _ => raise Fail "MLWorks Millet shim: Real.class")
    val fmt : StringCvt.realfmt -> real -> string = (fn _ => raise Fail "MLWorks Millet shim: Real.fmt")
    val toString : real -> string = (fn _ => raise Fail "MLWorks Millet shim: Real.toString")
    val fromString : string -> real option = (fn _ => raise Fail "MLWorks Millet shim: Real.fromString")
    val scan : (char, 'a) StringCvt.reader -> 'a -> (real * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Real.scan")
    val toManExp : real -> {man : real, exp : int} = (fn _ => raise Fail "MLWorks Millet shim: Real.toManExp")
    val fromManExp : {man : real, exp : int} -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.fromManExp")
    val split : real -> {whole : real, frac : real} = (fn _ => raise Fail "MLWorks Millet shim: Real.split")
    val realMod : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.realMod")
    val rem : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.rem")
    val nextAfter : real * real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.nextAfter")
    val checkFloat : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.checkFloat")
    val realFloor : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.realFloor")
    val realCeil : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.realCeil")
    val realTrunc : real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.realTrunc")
    val floor : real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.floor")
    val ceil : real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.ceil")
    val trunc : real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.trunc")
    val round : real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.round")
    val toInt : IEEEReal.rounding_mode -> real -> int = (fn _ => raise Fail "MLWorks Millet shim: Real.toInt")
    val toLargeInt : IEEEReal.rounding_mode -> real -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Real.toLargeInt")
    val fromInt : int -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.fromInt")
    val fromLargeInt : LargeInt.int -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.fromLargeInt")
    val toLarge : real -> LargeReal.real = (fn _ => raise Fail "MLWorks Millet shim: Real.toLarge")
    val fromLarge : IEEEReal.rounding_mode -> LargeReal.real -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.fromLarge")
    val toDecimal : real -> IEEEReal.decimal_approx = (fn _ => raise Fail "MLWorks Millet shim: Real.toDecimal")
    val fromDecimal : IEEEReal.decimal_approx -> real = (fn _ => raise Fail "MLWorks Millet shim: Real.fromDecimal")
  end

structure String =
  struct
    type char = char
    type string = string
    val maxSize : int = raise Fail "MLWorks Millet shim: String.maxSize"
    val size : string -> int = (fn _ => raise Fail "MLWorks Millet shim: String.size")
    val sub : (string * int) -> char = (fn _ => raise Fail "MLWorks Millet shim: String.sub")
    val extract : (string * int * int option) -> string = (fn _ => raise Fail "MLWorks Millet shim: String.extract")
    val concat : string list -> string = (fn _ => raise Fail "MLWorks Millet shim: String.concat")
    val op ^ : string * string -> string = (fn _ => raise Fail "MLWorks Millet shim: String.^")
    val implode : char list -> string = (fn _ => raise Fail "MLWorks Millet shim: String.implode")
    val explode : string -> char list = (fn _ => raise Fail "MLWorks Millet shim: String.explode")
    val translate : (char -> string) -> string -> string = (fn _ => raise Fail "MLWorks Millet shim: String.translate")
    val compare : (string * string) -> order = (fn _ => raise Fail "MLWorks Millet shim: String.compare")
    val str : char -> string = (fn _ => raise Fail "MLWorks Millet shim: String.str")
    val isPrefix : string -> string -> bool = (fn _ => raise Fail "MLWorks Millet shim: String.isPrefix")
    val substring : (string * int * int) -> string = (fn _ => raise Fail "MLWorks Millet shim: String.substring")
    val fields : (char -> bool) -> string -> string list = (fn _ => raise Fail "MLWorks Millet shim: String.fields")
    val tokens : (char -> bool) -> string -> string list = (fn _ => raise Fail "MLWorks Millet shim: String.tokens")
    val collate : (char * char -> order) -> (string * string) -> order = (fn _ => raise Fail "MLWorks Millet shim: String.collate")
    val map : ( char -> char) -> string -> string = (fn _ => raise Fail "MLWorks Millet shim: String.map")
    val mapi : (int * char -> char) -> string * int * int option -> string = (fn _ => raise Fail "MLWorks Millet shim: String.mapi")
    val fromString : string -> string option = (fn _ => raise Fail "MLWorks Millet shim: String.fromString")
    val toString : string -> string = (fn _ => raise Fail "MLWorks Millet shim: String.toString")
    val fromCString : string -> string option = (fn _ => raise Fail "MLWorks Millet shim: String.fromCString")
    val toCString : string -> string = (fn _ => raise Fail "MLWorks Millet shim: String.toCString")
    val op <= : string * string -> bool = (fn _ => raise Fail "MLWorks Millet shim: String.<=")
    val op < : string * string -> bool = (fn _ => raise Fail "MLWorks Millet shim: String.<")
    val op >= : string * string -> bool = (fn _ => raise Fail "MLWorks Millet shim: String.>=")
    val op > : string * string -> bool = (fn _ => raise Fail "MLWorks Millet shim: String.>")
  end

structure StringCvt =
  struct
    datatype radix = BIN | OCT | DEC | HEX
    datatype realfmt = EXACT | SCI of int option | FIX of int option | GEN of int option
    datatype cs = MLWorks_StringCvt_cs
    datatype ('a, 'b) reader = MLWorks_StringCvt_reader
    val scanString : ((char, cs) reader -> ('a, cs) reader) -> string -> 'a option = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.scanString")
    val skipWS : (char,'a) reader -> 'a -> 'a = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.skipWS")
    val padLeft : char -> int -> string -> string = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.padLeft")
    val padRight : char -> int -> string -> string = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.padRight")
    val scanList : ((char list -> (char * char list) option) -> char list -> ('a * 'b) option) -> char list -> 'a option = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.scanList")
    val splitl : (char -> bool) -> (char,'a) reader -> 'a -> (string * 'a) = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.splitl")
    val takel : (char -> bool) -> (char,'a) reader -> 'a -> string = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.takel")
    val dropl : (char -> bool) -> (char,'a) reader -> 'a -> 'a = (fn _ => raise Fail "MLWorks Millet shim: StringCvt.dropl")
  end

structure Substring =
  struct
    datatype substring = MLWorks_Substring_substring
    val base : substring -> (string * int * int) = (fn _ => raise Fail "MLWorks Millet shim: Substring.base")
    val string : substring -> string = (fn _ => raise Fail "MLWorks Millet shim: Substring.string")
    val substring : (string * int * int) -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.substring")
    val all : string -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.all")
    val isEmpty : substring -> bool = (fn _ => raise Fail "MLWorks Millet shim: Substring.isEmpty")
    val getc : substring -> (char * substring) option = (fn _ => raise Fail "MLWorks Millet shim: Substring.getc")
    val first : substring -> char option = (fn _ => raise Fail "MLWorks Millet shim: Substring.first")
    val triml : int -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.triml")
    val trimr : int -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.trimr")
    val slice : (substring * int * int option) -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.slice")
    val sub : (substring * int) -> char = (fn _ => raise Fail "MLWorks Millet shim: Substring.sub")
    val size : substring -> int = (fn _ => raise Fail "MLWorks Millet shim: Substring.size")
    val extract : string * int * int option -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.extract")
    val concat : substring list -> string = (fn _ => raise Fail "MLWorks Millet shim: Substring.concat")
    val explode : substring -> char list = (fn _ => raise Fail "MLWorks Millet shim: Substring.explode")
    val isPrefix : string -> substring -> bool = (fn _ => raise Fail "MLWorks Millet shim: Substring.isPrefix")
    val compare : (substring * substring) -> order = (fn _ => raise Fail "MLWorks Millet shim: Substring.compare")
    val collate : ((char * char) -> order) -> (substring * substring) -> order = (fn _ => raise Fail "MLWorks Millet shim: Substring.collate")
    val splitl : (char -> bool) -> substring -> (substring * substring) = (fn _ => raise Fail "MLWorks Millet shim: Substring.splitl")
    val splitr : (char -> bool) -> substring -> (substring * substring) = (fn _ => raise Fail "MLWorks Millet shim: Substring.splitr")
    val splitAt : (substring * int) -> (substring * substring) = (fn _ => raise Fail "MLWorks Millet shim: Substring.splitAt")
    val dropl : (char -> bool) -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.dropl")
    val dropr : (char -> bool) -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.dropr")
    val takel : (char -> bool) -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.takel")
    val taker : (char -> bool) -> substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.taker")
    val position : string -> substring -> (substring * substring) = (fn _ => raise Fail "MLWorks Millet shim: Substring.position")
    val translate : (char -> string) -> substring -> string = (fn _ => raise Fail "MLWorks Millet shim: Substring.translate")
    val tokens : (char -> bool) -> substring -> substring list = (fn _ => raise Fail "MLWorks Millet shim: Substring.tokens")
    val fields : (char -> bool) -> substring -> substring list = (fn _ => raise Fail "MLWorks Millet shim: Substring.fields")
    val foldl : ((char * 'a) -> 'a) -> 'a -> substring -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Substring.foldl")
    val foldr : ((char * 'a) -> 'a) -> 'a -> substring -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Substring.foldr")
    val app : (char -> unit) -> substring -> unit = (fn _ => raise Fail "MLWorks Millet shim: Substring.app")
    exception Span
    val span : substring * substring -> substring = (fn _ => raise Fail "MLWorks Millet shim: Substring.span")
  end

structure Time =
  struct
    datatype time = MLWorks_Time_time
    exception Time
    val zeroTime : time = raise Fail "MLWorks Millet shim: Time.zeroTime"
    val fromReal : LargeReal.real -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.fromReal")
    val toReal : time -> LargeReal.real = (fn _ => raise Fail "MLWorks Millet shim: Time.toReal")
    val toSeconds : time -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Time.toSeconds")
    val toMilliseconds : time -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Time.toMilliseconds")
    val toMicroseconds : time -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Time.toMicroseconds")
    val fromSeconds : LargeInt.int -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.fromSeconds")
    val fromMilliseconds : LargeInt.int -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.fromMilliseconds")
    val fromMicroseconds : LargeInt.int -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.fromMicroseconds")
    val compare : (time * time) -> order = (fn _ => raise Fail "MLWorks Millet shim: Time.compare")
    val op + : time * time -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.+")
    val op - : time * time -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.-")
    val op < : time * time -> bool = (fn _ => raise Fail "MLWorks Millet shim: Time.<")
    val op <= : time * time -> bool = (fn _ => raise Fail "MLWorks Millet shim: Time.<=")
    val op > : time * time -> bool = (fn _ => raise Fail "MLWorks Millet shim: Time.>")
    val op >= : time * time -> bool = (fn _ => raise Fail "MLWorks Millet shim: Time.>=")
    val now : unit -> time = (fn _ => raise Fail "MLWorks Millet shim: Time.now")
    val fmt : int -> time -> string = (fn _ => raise Fail "MLWorks Millet shim: Time.fmt")
    val toString : time -> string = (fn _ => raise Fail "MLWorks Millet shim: Time.toString")
    val fromString : string -> time option = (fn _ => raise Fail "MLWorks Millet shim: Time.fromString")
    val scan : (char, 'a) StringCvt.reader -> 'a -> (time * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Time.scan")
  end

structure Timer =
  struct
    datatype cpu_timer = MLWorks_Timer_cpu_timer
    datatype real_timer = MLWorks_Timer_real_timer
    val startCPUTimer : unit -> cpu_timer = (fn _ => raise Fail "MLWorks Millet shim: Timer.startCPUTimer")
    val totalCPUTimer : unit -> cpu_timer = (fn _ => raise Fail "MLWorks Millet shim: Timer.totalCPUTimer")
    val checkCPUTimer : cpu_timer -> {usr:Time.time, sys:Time.time} = (fn _ => raise Fail "MLWorks Millet shim: Timer.checkCPUTimer")
    val checkGCTime : cpu_timer -> Time.time = (fn _ => raise Fail "MLWorks Millet shim: Timer.checkGCTime")
    val startRealTimer : unit -> real_timer = (fn _ => raise Fail "MLWorks Millet shim: Timer.startRealTimer")
    val totalRealTimer : unit -> real_timer = (fn _ => raise Fail "MLWorks Millet shim: Timer.totalRealTimer")
    val checkRealTimer : real_timer -> Time.time = (fn _ => raise Fail "MLWorks Millet shim: Timer.checkRealTimer")
  end

structure Vector =
  struct
    datatype 'a vector = MLWorks_Vector_vector
    val maxLen : int = raise Fail "MLWorks Millet shim: Vector.maxLen"
    val fromList : 'a list -> 'a vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.fromList")
    val tabulate : (int * (int -> 'a)) -> 'a vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.tabulate")
    val length : 'a vector -> int = (fn _ => raise Fail "MLWorks Millet shim: Vector.length")
    val sub : ('a vector * int) -> 'a = (fn _ => raise Fail "MLWorks Millet shim: Vector.sub")
    val extract : ('a vector * int * int option) -> 'a vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.extract")
    val concat : 'a vector list -> 'a vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.concat")
    val appi : ((int * 'a) -> unit) -> ('a vector * int * int option) -> unit = (fn _ => raise Fail "MLWorks Millet shim: Vector.appi")
    val app : ('a -> unit) -> 'a vector -> unit = (fn _ => raise Fail "MLWorks Millet shim: Vector.app")
    val foldli : ((int * 'a * 'b) -> 'b) -> 'b -> ('a vector * int * int option) -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Vector.foldli")
    val foldri : ((int * 'a * 'b) -> 'b) -> 'b -> ('a vector * int * int option) -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Vector.foldri")
    val foldl : (('a * 'b) -> 'b) -> 'b -> 'a vector -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Vector.foldl")
    val foldr : (('a * 'b) -> 'b) -> 'b -> 'a vector -> 'b = (fn _ => raise Fail "MLWorks Millet shim: Vector.foldr")
    val map : ('a -> 'b) -> 'a vector -> 'b vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.map")
    val mapi : (int * 'a -> 'b) -> 'a vector * int * int option -> 'b vector = (fn _ => raise Fail "MLWorks Millet shim: Vector.mapi")
  end

structure Word =
  struct
    type word = word
    val wordSize : int = raise Fail "MLWorks Millet shim: Word.wordSize"
    val toLargeWord : word -> LargeWord.word = (fn _ => raise Fail "MLWorks Millet shim: Word.toLargeWord")
    val toLargeWordX : word -> LargeWord.word = (fn _ => raise Fail "MLWorks Millet shim: Word.toLargeWordX")
    val fromLargeWord : LargeWord.word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.fromLargeWord")
    val toLargeInt : word -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Word.toLargeInt")
    val toLargeIntX : word -> LargeInt.int = (fn _ => raise Fail "MLWorks Millet shim: Word.toLargeIntX")
    val fromLargeInt : LargeInt.int -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.fromLargeInt")
    val toInt : word -> int = (fn _ => raise Fail "MLWorks Millet shim: Word.toInt")
    val toIntX : word -> int = (fn _ => raise Fail "MLWorks Millet shim: Word.toIntX")
    val fromInt : int -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.fromInt")
    val orb : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.orb")
    val xorb : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.xorb")
    val andb : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.andb")
    val notb : word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.notb")
    val op << : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.<<")
    val op >> : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.>>")
    val op ~>> : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.~>>")
    val op + : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.+")
    val op - : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.-")
    val op * : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.*")
    val op div : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.div")
    val op mod : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.mod")
    val compare : word * word -> order = (fn _ => raise Fail "MLWorks Millet shim: Word.compare")
    val op > : word * word -> bool = (fn _ => raise Fail "MLWorks Millet shim: Word.>")
    val op >= : word * word -> bool = (fn _ => raise Fail "MLWorks Millet shim: Word.>=")
    val op < : word * word -> bool = (fn _ => raise Fail "MLWorks Millet shim: Word.<")
    val op <= : word * word -> bool = (fn _ => raise Fail "MLWorks Millet shim: Word.<=")
    val min : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.min")
    val max : word * word -> word = (fn _ => raise Fail "MLWorks Millet shim: Word.max")
    val fmt : StringCvt.radix -> word -> string = (fn _ => raise Fail "MLWorks Millet shim: Word.fmt")
    val toString : word -> string = (fn _ => raise Fail "MLWorks Millet shim: Word.toString")
    val fromString : string -> word option = (fn _ => raise Fail "MLWorks Millet shim: Word.fromString")
    val scan : StringCvt.radix -> (char, 'a) StringCvt.reader -> 'a -> (word * 'a) option = (fn _ => raise Fail "MLWorks Millet shim: Word.scan")
  end

structure MLWorks =
  struct
    structure Internal =
      struct
        structure Bits =
          struct
            val andb : int * int -> int = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Bits.andb"
          end

        structure Array =
          struct
            type 'a array = 'a Array.array
            val array : int * 'a -> 'a array = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Array.array"
            val arrayoflist : 'a list -> 'a array = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Array.arrayoflist"
            val length : 'a array -> int = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Array.length"
            val sub : 'a array * int -> 'a = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Array.sub"
            val update : 'a array * int * 'a -> unit = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Array.update"
          end

        structure ExtendedArray =
          struct
            type 'a array = 'a Array.array
            val array : int * 'a -> 'a array = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.array"
            val length : 'a array -> int = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.length"
            val sub : 'a array * int -> 'a = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.sub"
            val update : 'a array * int * 'a -> unit = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.update"
            val reducel : ('b * 'a -> 'b) -> 'b * 'a array -> 'b = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.reducel"
            val iterate : ('a -> unit) -> 'a array -> unit = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.iterate"
            val iterate_index : (int * 'a -> unit) -> 'a array -> unit = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.iterate_index"
            val map_index : (int * 'a -> 'b) -> 'a array -> 'b array = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.ExtendedArray.map_index"
          end

        structure Value =
          struct
            val unsafe_array_sub : 'a Array.array * int -> 'a = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Value.unsafe_array_sub"
            val unsafe_array_update : 'a Array.array * int * 'a -> unit = fn _ => raise Fail "MLWorks Millet shim: MLWorks.Internal.Value.unsafe_array_update"
          end
      end
  end

(* MLWorks keeps these old Basis aliases available at top level. *)
val chr : int -> char = Char.chr
val ord : char -> int = Char.ord
val explode : string -> char list = String.explode
val implode : char list -> string = String.implode
val concat : string list -> string = String.concat
val size : string -> int = String.size
val substring : string * int * int -> string = String.substring
